
/*
Ejemplo de %TYPE
*/

CREATE OR REPLACE FUNCTION SCOTT.FN_NOMBRE
( P_CODIGO IN SCOTT.EMP.EMPNO%TYPE )
RETURN VARCHAR2
AS

  V_NOMBRE SCOTT.EMP.ENAME%TYPE;
  V_CONTA  NUMBER(5);

BEGIN

  SELECT COUNT(1) INTO V_CONTA 
  FROM SCOTT.EMP 
  WHERE EMPNO = P_CODIGO;

  IF V_CONTA = 1 THEN
    SELECT NVL(ENAME,'NO TIENE') INTO V_NOMBRE 
    FROM SCOTT.EMP 
    WHERE EMPNO = P_CODIGO; 
  ELSE
    V_NOMBRE := 'NO EXISTE';
  END IF;  
  
  RETURN V_NOMBRE;
  
END;
/


SELECT SCOTT.FN_NOMBRE(44444) FROM DUAL;

SELECT SCOTT.FN_NOMBRE(7777) FROM DUAL;

SELECT SCOTT.FN_NOMBRE(7521) FROM DUAL;


SELECT * FROM SCOTT.EMP;


INSERT INTO SCOTT.EMP( EMPNO, SAL )
VALUES( 7777, 55555 );



/*
Tarea 04
Desarrollar una funcion que retorne los ingresos totales
de un empleado. Esquema RECURSOS.
*/


