CREATE SEQUENCE SEQ_NIVEL_ESTUDIOS
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999
  MINVALUE 1;
  
  
CREATE SEQUENCE SEQ_TIPO_INSTITUCION_ACAD
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999
  MINVALUE 1;
  
  
  CREATE SEQUENCE SEQ_NIVEL_ALCANZADO
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_INSTITUCION_ACADEMICA
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_AREA
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_CARGO
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_PREGUNTAS_DJ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_TIPO_ESPECIALIZACION
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999
  MINVALUE 1;
  
  -- NUEVOS SEQUENCES PARA PERFILES
  
  CREATE SEQUENCE SEQ_PERFIL_AREA
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_PERFIL_CARGO
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_PERFIL_ESPECIALIDAD
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_PERFIL_INSTITUCION
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_PERFIL_NIVEL
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_PERFIL_TIPO_ESPECIALIZA
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;
  
    CREATE SEQUENCE SEQ_ESPECIALIDAD
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;
  
  CREATE SEQUENCE SEQ_CONVOCATORIA
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 99999999
  MINVALUE 1;