




-- ==========================================================
-- 1. Crear la Tabla: RHTM_ESTADO_CIVIL
-- ==========================================================


CREATE TABLE "RHTM_ESTADO_CIVIL" 
   (  "CO_ESTADO_CIVIL" NUMBER(*,0) NOT NULL ENABLE, 
  "DE_ESTADO_CIVIL" VARCHAR2(50) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" CHAR(8), 
  "FE_CREACION" DATE, 
  "US_UPDATE" CHAR(8), 
  "FE_UPDATE" DATE, 
   CONSTRAINT "CP_ESTADO_CIVIL" PRIMARY KEY ("CO_ESTADO_CIVIL")
  
   );

   COMMENT ON COLUMN "RHTM_ESTADO_CIVIL"."CO_ESTADO_CIVIL" IS 'CODIGO DE ESTADO CIVIL';
 
   COMMENT ON COLUMN "RHTM_ESTADO_CIVIL"."DE_ESTADO_CIVIL" IS 'DESCRIPCION DE ESTADO CIVIL';
 
   COMMENT ON COLUMN "RHTM_ESTADO_CIVIL"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTM_ESTADO_CIVIL"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_ESTADO_CIVIL"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_ESTADO_CIVIL"."US_UPDATE" IS 'USUARIO MODIFICACOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_ESTADO_CIVIL"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
   
   
-- ==========================================================
-- 2. Crear la Tabla de Información de Postulantes: RHTM_POSTULANTE
-- ==========================================================
CREATE TABLE "RHTM_POSTULANTE" 
   (  "NU_DNI" CHAR(8) NOT NULL ENABLE, 
  "AP_PATERNO" VARCHAR2(50) NOT NULL ENABLE, 
  "AP_MATERNO" VARCHAR2(50) NOT NULL ENABLE, 
  "NO_PRENOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
  "IN_GENERO" CHAR(1) NOT NULL ENABLE, 
  "CO_ESTADO_CIVIL" NUMBER(*,0) NOT NULL ENABLE, 
  "FE_NAC" DATE NOT NULL ENABLE, 
  "US_CREACION" CHAR(8), 
  "FE_CREACION" DATE, 
  "US_UPDATE" CHAR(8), 
  "FE_UPDATE" DATE, 
   CONSTRAINT "CP_POSTULANTE" PRIMARY KEY ("NU_DNI")
   );

   COMMENT ON COLUMN "RHTM_POSTULANTE"."NU_DNI" IS 'NUMERO DE DNI';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."AP_PATERNO" IS 'APELLIDO PATERNO';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."AP_MATERNO" IS 'APELLIDO MATERNO';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."NO_PRENOMBRE" IS 'NOMBRE';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."IN_GENERO" IS 'INDICADOR DE GENERO (1 MASCULINO  2 FEMENINO)';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."CO_ESTADO_CIVIL" IS 'CODIGO DE ESTADO CIVIL';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."FE_NAC" IS 'FECHA DE NACIMIENTO';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."FE_CREACION" IS 'FECHA DE CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_POSTULANTE"."FE_UPDATE" IS 'FECHA DE MODIFICACION DEL REGISTRO';
   
   ALTER TABLE "RHTM_POSTULANTE"
   ADD CONSTRAINT "FK_CO_ESTADO_CIVIL"
   FOREIGN KEY (CO_ESTADO_CIVIL)
   REFERENCES "RHTM_ESTADO_CIVIL" (CO_ESTADO_CIVIL);
   
   
-- ==========================================================
-- 3. Crear la Tabla de Etapas Convocatoria: RHTR_ETAPA_CONV
-- ==========================================================

CREATE TABLE "RHTR_ETAPA_CONV" 
   (  "CO_ETAPA" NUMBER(*,0) NOT NULL ENABLE, 
  "DE_ETAPA" VARCHAR2(50) NOT NULL ENABLE, 
  "US_CREACION" CHAR(8), 
  "FE_CREACION" DATE, 
  "US_UPDATE" CHAR(8), 
  "FE_UPDATE" DATE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
   CONSTRAINT "CP_ETAPA_CONV" PRIMARY KEY ("CO_ETAPA")
   ) ;

   COMMENT ON COLUMN "RHTR_ETAPA_CONV"."CO_ETAPA" IS 'CODIGO DE LA ETAPA';
 
   COMMENT ON COLUMN "RHTR_ETAPA_CONV"."DE_ETAPA" IS 'DESCRIPCION DE LA ETAPA';
 
   COMMENT ON COLUMN "RHTR_ETAPA_CONV"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_ETAPA_CONV"."FE_CREACION" IS 'FECHA DE CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_ETAPA_CONV"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_ETAPA_CONV"."FE_UPDATE" IS 'FECHA DE MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_ETAPA_CONV"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVA  2 INACTIVA)';
   
   
-- ==========================================================
-- 4. Crear la Tabla Tipo Convocatoria: RHTR_TIPO_CONV
-- ==========================================================

CREATE TABLE "RHTR_TIPO_CONV" 
   (  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "DE_TIPO" VARCHAR2(50) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
   CONSTRAINT "PK_TIPO_CONV" PRIMARY KEY ("CO_TIPO")
   ) ;

   COMMENT ON COLUMN "RHTR_TIPO_CONV"."CO_TIPO" IS 'CODIGO DEL TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTR_TIPO_CONV"."DE_TIPO" IS 'DESCRIPCION DEL TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTR_TIPO_CONV"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_TIPO_CONV"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_TIPO_CONV"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_TIPO_CONV"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTR_TIPO_CONV"."IN_ESTADO" IS 'ESTADO DEL RIPO DE CONVOCATORIA (1 ACTIVO  0 INACTIVO)';
  
  
-- ==========================================================
-- 5. Crear la Tabla : RHTM_CONVOCATORIA
-- ==========================================================

CREATE TABLE "RHTM_CONVOCATORIA" 
   (  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "DE_CONV" VARCHAR2(100) NOT NULL ENABLE, 
  "CO_UUOO" VARCHAR2(5) NOT NULL ENABLE, 
  "CO_UBICACION" VARCHAR2(20) NOT NULL ENABLE, 
  "FE_INI_CONV" DATE NOT NULL ENABLE, 
  "FE_FIN_CONV" DATE NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "CO_ETAPA" NUMBER(*,0), 
  "CO_TIPO" CHAR(1), 
  "SE_CONV" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_COLEGIATURA" CHAR(1), 
  "CA_ANOS_EXP_GEN" NUMBER(*,0), 
  "CA_ANOS_EXP_ESP" NUMBER(*,0), 
  "CO_SUB_GERENCIA" VARCHAR2(5), 
  "DE_UUOO" VARCHAR2(50), 
  "DE_UBICACION" VARCHAR2(80), 
   CONSTRAINT "CP_CONVOCATORIA" PRIMARY KEY ("NU_CONV", "ANO_CONV", "CO_TIPO"),
   CONSTRAINT "CF_CONVOCATORIA_01" FOREIGN KEY ("CO_ETAPA")
    REFERENCES "RHTR_ETAPA_CONV" ("CO_ETAPA") ENABLE, 
   CONSTRAINT "CF_CONVOCATORIA_02" FOREIGN KEY ("CO_TIPO")
    REFERENCES "RHTR_TIPO_CONV" ("CO_TIPO") ENABLE
   ) ;
 
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."DE_CONV" IS 'DESCRIPCION DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."CO_UUOO" IS 'CODIGO DE UUOO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."CO_UBICACION" IS 'CODIGO DE UBIGEO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."FE_INI_CONV" IS 'FECHA INICIO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."FE_FIN_CONV" IS 'FECHA FIN DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVA  0 INACTIVA)';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."CO_ETAPA" IS 'CODIGO DE ETAPA DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."SE_CONV" IS 'SECUENCIA DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."IN_COLEGIATURA" IS 'INDICADOR DE COLEGIATURA (1 NECESITA  0 NO NECESITA)';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."CA_ANOS_EXP_GEN" IS 'CANTIDAD DE AÑOS DE EXPERIENCIA GENERAL';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."CA_ANOS_EXP_ESP" IS 'CANTIDAD DE AÑOS DE EXPERIENCIA ESPECIFICA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."CO_SUB_GERENCIA" IS 'CODIGO DE LA SUBGERENCIA DE LA UUOO SELECCIONADA DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."DE_UUOO" IS 'DESCRIPCION DE LA UUOO(GERENCIA) SELECCIONADA';
 
   COMMENT ON COLUMN "RHTM_CONVOCATORIA"."DE_UBICACION" IS 'DESCRIPCION DEL UBIGEO SELECCIONADO PARA LA CONVOCATORIA';
 
 
-- ==========================================================
-- 6. Crear la Tabla : RHTM_TIPO_ESPECIALIZACION
-- ==========================================================
 CREATE TABLE "RHTM_TIPO_ESPECIALIZACION" 
   (  "CO_TIPO_ESP" NUMBER(*,0) NOT NULL ENABLE, 
  "DE_TIPO_ESP" VARCHAR2(50) NOT NULL ENABLE,
    "CA_HORAS_CON_ER" NUMBER(*,0) NOT NULL ENABLE, 
    "CA_HORAS_SIN_ER" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "NU_SECUENCIA" NUMBER(*,0), 
  "NU_ANIO" NUMBER(*,0), 
   CONSTRAINT "CP_TIPO_ESPECIALIZACION" PRIMARY KEY ("CO_TIPO_ESP")
   ) ;
   
-- ==========================================================
-- 7. Crear la Tabla : RHTM_TIPO_ESPECIALIZACION
-- ==========================================================
   CREATE TABLE "RHTM_ESPECIALIDAD" 
   (  "CO_ESPECIALIDAD" NUMBER(*,0) NOT NULL ENABLE, 
  "DE_ESPECIALIDAD" VARCHAR2(100) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "NU_SECUENCIA" NUMBER(*,0), 
  "NU_ANIO" NUMBER(*,0), 
   CONSTRAINT "CP_ESPECIALIDAD" PRIMARY KEY ("CO_ESPECIALIDAD")
   ) ;
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."CO_ESPECIALIDAD" IS 'CODIGO DE CARRERA PROFESIONAL';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."DE_ESPECIALIDAD" IS 'DESCRIPCION DE CARRERA PROFESIONAL';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVA  0 INACTIVA)';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."NU_SECUENCIA" IS 'NUMERO DE SECUENCIA DE LA TABLA, QUE SE REINICIA POR CADA AÑO';
 
   COMMENT ON COLUMN "RHTM_ESPECIALIDAD"."NU_ANIO" IS 'NUMERO DE AÑO DE ACUERDO AL VIGENTE';
 
-- ==========================================================
-- 8. Crear la Tabla : RHTM_TIPO_ESPECIALIZACION
-- ==========================================================

CREATE TABLE "RHTM_NIVEL_ESTUDIOS" 
   (	"CO_NIVEL" NUMBER(*,0) NOT NULL ENABLE, 
	"DE_NIVEL" VARCHAR2(50) NOT NULL ENABLE, 
	"IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
	"US_CREACION" VARCHAR2(20), 
	"FE_CREACION" DATE, 
	"US_UPDATE" VARCHAR2(20), 
	"FE_UPDATE" DATE, 
	"NU_SECUENCIA" NUMBER(*,0), 
	"NU_ANIO" NUMBER(*,0), 
	 CONSTRAINT "CP_NIVEL_ESTUDIOS" PRIMARY KEY ("CO_NIVEL")
   ) ;
 
-- ==========================================================
-- 9. Crear la Tabla : RHTM_TIPO_ESPECIALIZACION
-- ==========================================================

CREATE TABLE "RHTM_CARGO" 
   (	"CO_CARGO" NUMBER(*,0) NOT NULL ENABLE, 
	"DE_CARGO" VARCHAR2(200) NOT NULL ENABLE, 
	"IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
	"US_CREACION" VARCHAR2(20), 
	"FE_CREACION" DATE, 
	"US_UPDATE" VARCHAR2(20), 
	"FE_UPDATE" DATE, 
	"NU_ANIO" NUMBER(*,0), 
	"NU_SECUENCIA" NUMBER(*,0), 
	 CONSTRAINT "CP_CARGO" PRIMARY KEY ("CO_CARGO")
   ) ;
 
   COMMENT ON COLUMN "RHTM_CARGO"."CO_CARGO" IS 'CODIGO DEL CARGO';
 
   COMMENT ON COLUMN "RHTM_CARGO"."DE_CARGO" IS 'DESCRIPCION DEL CARGO';
 
   COMMENT ON COLUMN "RHTM_CARGO"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTM_CARGO"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CARGO"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CARGO"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CARGO"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CARGO"."NU_ANIO" IS 'NUMERO DE AÑO REGISTRO';
 
   COMMENT ON COLUMN "RHTM_CARGO"."NU_SECUENCIA" IS 'NUMERO DE SECUENCIA';
 

-- ==========================================================
-- 10. Crear la Tabla : RHTM_TIPO_ESPECIALIZACION
-- ==========================================================

CREATE TABLE "RHTM_AREA" 
   (	"CO_AREA" NUMBER(*,0) NOT NULL ENABLE, 
	"DE_AREA" VARCHAR2(200) NOT NULL ENABLE, 
	"IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
	"US_CREACION" VARCHAR2(20), 
	"FE_CREACION" DATE, 
	"US_UPDATE" VARCHAR2(20), 
	"FE_UPDATE" DATE, 
	"NU_SECUENCIA" NUMBER(*,0), 
	"NU_ANIO" NUMBER(*,0), 
	 CONSTRAINT "CP_AREA" PRIMARY KEY ("CO_AREA")
   ) ;
 
   COMMENT ON COLUMN "RHTM_AREA"."CO_AREA" IS 'CODIGO DE AREA';
 
   COMMENT ON COLUMN "RHTM_AREA"."DE_AREA" IS 'DESCRIPCION DE AREA';
 
   COMMENT ON COLUMN "RHTM_AREA"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTM_AREA"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_AREA"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_AREA"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_AREA"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_AREA"."NU_SECUENCIA" IS 'NUMERO DE SECUENCIA';
 
   COMMENT ON COLUMN "RHTM_AREA"."NU_ANIO" IS 'NUMERO DE AÑO';
 
-- ==========================================================
-- 11. Crear la Tabla : RHTM_TIPO_ESPECIALIZACION
-- ==========================================================

CREATE TABLE "RHTM_NIVEL_ALCANZADO" 
   (  "CO_NIVEL_ALC" NUMBER(*,0) NOT NULL ENABLE, 
  "DE_NIVEL_ALC" VARCHAR2(50) NOT NULL ENABLE, 
  "CO_NIVEL" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "NU_SECUENCIA" NUMBER(*,0), 
  "NU_ANIO" NUMBER(*,0), 
   CONSTRAINT "CP_NIVEL_ALCANZADO" PRIMARY KEY ("CO_NIVEL_ALC"), 
   CONSTRAINT "CF_NIVEL_ALCANZADO_01" FOREIGN KEY ("CO_NIVEL")
    REFERENCES "RHTM_NIVEL_ESTUDIOS" ("CO_NIVEL") ENABLE
   ) ;
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."CO_NIVEL_ALC" IS 'CODIGO DE NIVEL ALCANZADO';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."DE_NIVEL_ALC" IS 'DESCRIPCION DE NIVEL ALCANZADO';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."CO_NIVEL" IS 'CODIGO DE NIVEL DE ESTUDIOS';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."NU_SECUENCIA" IS 'NUMERO DE SECUENCIA';
 
   COMMENT ON COLUMN "RHTM_NIVEL_ALCANZADO"."NU_ANIO" IS 'NUMERO DE AÑO';
 
-- ==========================================================
-- 12. Crear la Tabla : RHTM_TIPO_ESPECIALIZACION
-- ==========================================================

CREATE TABLE "RHTR_TIPO_INSTITUCION_ACAD" 
   (	"CO_TIPO_INST" NUMBER(*,0) NOT NULL ENABLE, 
	"DE_TIPO_INST" VARCHAR2(50) NOT NULL ENABLE,
	"IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
	"US_CREACION" VARCHAR2(20), 
	"FE_CREACION" DATE, 
	"US_UPDATE" VARCHAR2(20), 
	"FE_UPDATE" DATE, 
	"NU_SECUENCIA" NUMBER(*,0), 
	"NU_ANIO" NUMBER(*,0), 
	 CONSTRAINT "CP_TIPO_INSTITUCION_ACAD" PRIMARY KEY ("CO_TIPO_INST")
   ) ;


-- ==========================================================
-- 13. Crear la Tabla : 
-- ==========================================================

CREATE TABLE "RHTD_PERFIL_CARGO" 
   (  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "CO_CARGO" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "SEC_PERFIL_CARGO" NUMBER(*,0), 
   CONSTRAINT "CP_PERFIL_CARGO" PRIMARY KEY ("NU_CONV", "ANO_CONV", "CO_TIPO", "CO_CARGO", "SEC_PERFIL_CARGO"), 
   CONSTRAINT "CF_PERFIL_CARGO_01" FOREIGN KEY ("CO_CARGO")
    REFERENCES "RHTM_CARGO" ("CO_CARGO") ENABLE, 
   CONSTRAINT "CF_PERFIL_CARGO_02" FOREIGN KEY ("NU_CONV", "ANO_CONV", "CO_TIPO")
    REFERENCES "RHTM_CONVOCATORIA" ("NU_CONV", "ANO_CONV", "CO_TIPO") ENABLE
   ) ;

   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."CO_CARGO" IS 'CODIGO DEL CARGO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_CARGO"."SEC_PERFIL_CARGO" IS 'CODIGO DE PERFIL DE CARGO';
 
-- ==========================================================
-- 14. Crear la Tabla : 
-- ==========================================================

CREATE TABLE "RHTD_PERFIL_AREA" 
   (  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "CO_AREA" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "SEC_PERFIL_AREA" NUMBER(*,0), 
   CONSTRAINT "CP_PERFIL_AREA" PRIMARY KEY ("NU_CONV", "ANO_CONV", "CO_TIPO", "CO_AREA", "SEC_PERFIL_AREA"), 
   CONSTRAINT "CF_PERFIL_AREA_01" FOREIGN KEY ("CO_AREA")
    REFERENCES "RHTM_AREA" ("CO_AREA") ENABLE, 
   CONSTRAINT "CF_PERFIL_AREA_02" FOREIGN KEY ("NU_CONV", "ANO_CONV", "CO_TIPO")
    REFERENCES "RHTM_CONVOCATORIA" ("NU_CONV", "ANO_CONV", "CO_TIPO") ENABLE
   ) ;
 
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."CO_AREA" IS 'CODIGO DE AREA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."IN_ESTADO" IS 'INDICADOR DE ESTADO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_AREA"."SEC_PERFIL_AREA" IS 'CODIGO DE PERFIL DE AREA';
 

-- ==========================================================
-- 15. Crear la Tabla : 
-- ==========================================================

CREATE TABLE "RHTD_PERFIL_NIVEL" 
   (  "CO_NIVEL_ALC" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "SEC_PERFIL_NIVEL" NUMBER(*,0), 
   CONSTRAINT "CP_PERFIL_NIVEL" PRIMARY KEY ("CO_NIVEL_ALC", "NU_CONV", "ANO_CONV", "CO_TIPO", "SEC_PERFIL_NIVEL"), 
   CONSTRAINT "CF_PERFIL_NIVEL_01" FOREIGN KEY ("CO_NIVEL_ALC")
    REFERENCES "RHTM_NIVEL_ALCANZADO" ("CO_NIVEL_ALC") ENABLE, 
   CONSTRAINT "CF_PERFIL_NIVEL_02" FOREIGN KEY ("NU_CONV", "ANO_CONV", "CO_TIPO")
    REFERENCES "RHTM_CONVOCATORIA" ("NU_CONV", "ANO_CONV", "CO_TIPO") ENABLE
   )  ;
 
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."CO_NIVEL_ALC" IS 'CODIGO DE NIVEL DE ESTUDIOS ALCANZADO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_NIVEL"."SEC_PERFIL_NIVEL" IS 'CODIGO DE PERFIL DE NIVEL';
 

-- ==========================================================
-- 16. Crear la Tabla : 
-- ==========================================================
CREATE TABLE "RHTM_INSTITUCION_ACADEMICA" 
   (  "CO_INSTITUCION" NUMBER(*,0) NOT NULL ENABLE, 
  "DE_INSTITUCION" VARCHAR2(100) NOT NULL ENABLE, 
  "CO_TIPO_INST" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "NU_SECUENCIA" NUMBER(*,0), 
  "NU_ANIO" NUMBER(*,0), 
   CONSTRAINT "CP_INSTITUCION_ACADEMICA" PRIMARY KEY ("CO_INSTITUCION"), 
   CONSTRAINT "CF_INSTITUCION_ACADEMICA_01" FOREIGN KEY ("CO_TIPO_INST")
    REFERENCES "RHTR_TIPO_INSTITUCION_ACAD" ("CO_TIPO_INST") ENABLE
   )  ;
 
   
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."CO_INSTITUCION" IS 'CODIGO DE INSTITUCION';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."DE_INSTITUCION" IS 'DESCRIPCION DE INSTITUCION';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."CO_TIPO_INST" IS 'CODIGO DE TIPO DE INSTITUCION';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVA  0 INACTIVA)';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."NU_SECUENCIA" IS 'NUMERO DE SECUENCIA';
 
   COMMENT ON COLUMN "RHTM_INSTITUCION_ACADEMICA"."NU_ANIO" IS 'NUMERO DE AÑO';
 

-- ==========================================================
-- 17. Crear la Tabla : 
-- ==========================================================
CREATE TABLE "RHTD_PERFIL_TIPO_ESPECIALIZA" 
   (  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "CO_TIPO_ESP" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" CHAR(8), 
  "FE_CREACION" DATE, 
  "US_UPDATE" CHAR(8), 
  "FE_UPDATE" DATE, 
  "SEC_PERFIL_TIPO_ESPECIALIZA" NUMBER(*,0), 
   CONSTRAINT "CP_PERFIL_TIPO_ESPECIALIZA" PRIMARY KEY ("NU_CONV", "ANO_CONV", "CO_TIPO", "CO_TIPO_ESP", "SEC_PERFIL_TIPO_ESPECIALIZA"), 
   CONSTRAINT "CF_PERFIL_TIPO_ESPECIALIZA_01" FOREIGN KEY ("CO_TIPO_ESP")
    REFERENCES "RHTM_TIPO_ESPECIALIZACION" ("CO_TIPO_ESP") ENABLE, 
   CONSTRAINT "CF_PERFIL_TIPO_ESPECIALIZA_02" FOREIGN KEY ("NU_CONV", "ANO_CONV", "CO_TIPO")
    REFERENCES "RHTM_CONVOCATORIA" ("NU_CONV", "ANO_CONV", "CO_TIPO") ENABLE
   ) ;
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."CO_TIPO_ESP" IS 'CODIGO DE TIPO DE ESPECIALIZACION';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_TIPO_ESPECIALIZA"."SEC_PERFIL_TIPO_ESPECIALIZA" IS 'CODIGO DE PERFIL DE TIPO DE ESPECIALIZACION';
 

-- ==========================================================
-- 18. Crear la Tabla : 
-- ==========================================================
CREATE TABLE "RHTD_PERFIL_INSTITUCION" 
   (  "CO_TIPO_INST" NUMBER(*,0) NOT NULL ENABLE, 
  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "SEC_PERFIL_INSTITUCION" NUMBER(*,0), 
   CONSTRAINT "CP_PERFIL_INSTITUCION" PRIMARY KEY ("CO_TIPO_INST", "NU_CONV", "ANO_CONV", "CO_TIPO", "SEC_PERFIL_INSTITUCION"), 
   CONSTRAINT "CF_PERFIL_INSTITUCION_01" FOREIGN KEY ("CO_TIPO_INST")
    REFERENCES "RHTR_TIPO_INSTITUCION_ACAD" ("CO_TIPO_INST") ENABLE, 
   CONSTRAINT "CF_PERFIL_INSTITUCION_02" FOREIGN KEY ("NU_CONV", "ANO_CONV", "CO_TIPO")
    REFERENCES "RHTM_CONVOCATORIA" ("NU_CONV", "ANO_CONV", "CO_TIPO") ENABLE
   ) ;
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."CO_TIPO_INST" IS 'CODIGO DEL TIPO DE INSTITUCION';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  00 INACTIVO)';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_INSTITUCION"."SEC_PERFIL_INSTITUCION" IS 'CODIGO DE PERFIL DE INSTITUCION';
 

-- ==========================================================
-- 19. Crear la Tabla : 
-- ==========================================================
CREATE TABLE "RHTD_POSTULA_CONV" 
   (  "NU_DNI" CHAR(8) NOT NULL ENABLE, 
  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4), 
  "CO_TIPO" CHAR(1), 
  "US_CREACION" CHAR(8), 
  "FE_CREACION" DATE, 
  "US_UPDATE" CHAR(8), 
  "FE_UPDATE" DATE, 
  "AP_PATERNO" VARCHAR2(50) NOT NULL ENABLE, 
  "AP_MATERNO" VARCHAR2(50) NOT NULL ENABLE, 
  "NO_PRENOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
  "IN_GENERO" CHAR(1) NOT NULL ENABLE, 
  "CO_ESTADO_CIVIL" NUMBER(*,0) NOT NULL ENABLE, 
  "FE_NAC" DATE NOT NULL ENABLE, 
  "NU_RUC" CHAR(11) NOT NULL ENABLE, 
  "DE_EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
  "DE_EMAIL_ALTER" VARCHAR2(100), 
  "DE_DIRECCION" VARCHAR2(100) NOT NULL ENABLE, 
  "CO_TELEFONO" VARCHAR2(3), 
  "NU_TELEFONO" VARCHAR2(25), 
  "NU_CELULAR" VARCHAR2(25), 
  "CO_UBIGEO" VARCHAR2(20) NOT NULL ENABLE, 
  "IN_DISCAPA" CHAR(1) NOT NULL ENABLE, 
  "NO_RESOL" VARCHAR2(100), 
  "IN_LIC_FFAA" CHAR(1) NOT NULL ENABLE, 
  "DE_LIC_FFAA" VARCHAR2(100), 
  "IN_COLEGIADO" CHAR(1) NOT NULL ENABLE, 
  "NO_COLEGIO" VARCHAR2(100), 
  "NU_COLEGIATURA" VARCHAR2(20), 
  "IN_HABIL_COLEGIO" CHAR(1), 
  "FE_EGRESO" DATE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "NU_FICHA" CHAR(6), 
  "PDF_FICHA" BLOB, 
  "ANO_FICHA" CHAR(4), 
  "SE_POSTULA_CONV" NUMBER(*,0), 
   CONSTRAINT "CP_POSTULA_CONV" PRIMARY KEY ("NU_DNI", "NU_CONV", "ANO_CONV", "CO_TIPO"), 
   CONSTRAINT "CF_POSTULA_CONV_02" FOREIGN KEY ("NU_CONV", "ANO_CONV", "CO_TIPO")
    REFERENCES "RHTM_CONVOCATORIA" ("NU_CONV", "ANO_CONV", "CO_TIPO") ENABLE, 
   CONSTRAINT "CF_POSTULA_CONV_01" FOREIGN KEY ("CO_ESTADO_CIVIL")
    REFERENCES "RHTM_ESTADO_CIVIL" ("CO_ESTADO_CIVIL") ENABLE
   )  ;
 
  --CREATE UNIQUE INDEX "CP_POSTULA_CONV" ON "RHTD_POSTULA_CONV" ("NU_DNI", "NU_CONV", "ANO_CONV", "CO_TIPO") ;
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NU_DNI" IS 'NUMERO DE DNI DE POSTULANTE';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."AP_PATERNO" IS 'APELLIDO PATERNO DEL POSTULANTE';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."AP_MATERNO" IS 'APELLIDO MATERNO DEL POSTULANTE';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NO_PRENOMBRE" IS 'NOMBRE DEL POSTULANTE';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."IN_GENERO" IS 'INDICADOR DEL GENERO (1 MASCULINO  2 FEMENINO)';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."CO_ESTADO_CIVIL" IS 'CODIGO DE ESTADO CIVIL';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."FE_NAC" IS 'FECHA DE NACIMIENTO DEL POSTULANTE';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NU_RUC" IS 'NUMERO DE RUC';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."DE_EMAIL" IS 'CORREO ELECTRONICO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."DE_EMAIL_ALTER" IS 'CORREO ELECTRONICO ALTERNATVO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."DE_DIRECCION" IS 'DIRECCION';
 
   COMMENT ON COLUMN "IDO_RRHH"."RHTD_POSTULA_CONV"."CO_TELEFONO" IS 'CODIGO DE TELEFONO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NU_TELEFONO" IS 'NUMERO DE TELEFONO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NU_CELULAR" IS 'NUMERO DE CELULAR';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."CO_UBIGEO" IS 'CODIGO DE UBIGEO';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."IN_DISCAPA" IS 'INDICADOR DE DISCAPACIDAD (1 DISCAPACITADO  0 SIN DISCAPACIDAD)';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NO_RESOL" IS 'NOMBRE DE RESOLUCION DE DISCAPACIDAD';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."IN_LIC_FFAA" IS 'INDICADOR DE LICENCIADO FFAA (1 LICENCIADO  0 NO LICENCIADO)';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."DE_LIC_FFAA" IS 'DESCRIPCION DE RESOLUCION DE LIC. FFAA';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."IN_COLEGIADO" IS 'INDICADOR DE COLEGIATURA (1 COLEGIADO  0 NO COLEGIADO)';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NO_COLEGIO" IS 'NOMBRE DEL COLEGIO PROFESIONAL';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NU_COLEGIATURA" IS 'NUMERO DE COLEGIATURA';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."IN_HABIL_COLEGIO" IS 'INDICADOR DE HABILITADO EN COLEGIO PROFESIONAL (1 HABILITADO  0 INHABILITADO)';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."FE_EGRESO" IS 'FECHA DE EGRESO DE LA INSTITUCION ACADEMICA';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."IN_ESTADO" IS 'INDICADOR DE ESTADO DEL POSTULANTE EN LA CONVOCATORIA (1 REGISTRO WEB  2 CV RECEPCIONADO)';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."NU_FICHA" IS 'NUMERO DE REGISTRO DE FICHA DEL POSTULANTE';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."PDF_FICHA" IS 'FICHA RESUMEN DEL POSTULANTE EN PDF';
 
   COMMENT ON COLUMN "RHTD_POSTULA_CONV"."ANO_FICHA" IS 'AÑO DE  REGISTRO DE FICHA DEL POSTULANTE';
 
   COMMENT ON COLUMN"RHTD_POSTULA_CONV"."SE_POSTULA_CONV" IS 'SECUENCIA DE POSTULACIONES EN LA CONVOCATORIA';
 

-- ==========================================================
-- 20. Crear la Tabla : 
-- ==========================================================
 
 CREATE TABLE "RHTD_ESPECIALIZACION" 
    ( "NU_DNI" CHAR(8) NOT NULL ENABLE, 
  "SE_ESPECIALIZACION" NUMBER(*,0) NOT NULL ENABLE, 
  "DE_ESPECIALIZACION" VARCHAR2(100) NOT NULL ENABLE, 
  "NO_INSTITUCION" VARCHAR2(100) NOT NULL ENABLE, 
  "CA_HORAS" NUMBER(*,0) NOT NULL ENABLE, 
  "CO_TIPO_ESP" NUMBER(*,0) NOT NULL ENABLE, 
  "US_CREACION" CHAR(8), 
  "FE_CREACION" DATE, 
  "US_UPDATE" CHAR(8), 
  "FE_UPDATE" DATE, 
  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "IN_ER" CHAR(1) NOT NULL ENABLE, 
   CONSTRAINT "CP_ESPECIALIZACION" PRIMARY KEY ("NU_DNI", "SE_ESPECIALIZACION", "NU_CONV", "ANO_CONV", "CO_TIPO"), 
   CONSTRAINT "CF_ESPECIALIZACION_02" FOREIGN KEY ("NU_DNI", "NU_CONV", "ANO_CONV", "CO_TIPO")
    REFERENCES "RHTD_POSTULA_CONV" ("NU_DNI", "NU_CONV", "ANO_CONV", "CO_TIPO") ENABLE, 
   CONSTRAINT "CF_ESPECIALIZACION_01" FOREIGN KEY ("CO_TIPO_ESP")
    REFERENCES "RHTM_TIPO_ESPECIALIZACION" ("CO_TIPO_ESP") ENABLE
    ) ;
  
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."NU_DNI" IS 'NUMERO DE DNI DEL POSTULANTE';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."SE_ESPECIALIZACION" IS 'SECUENCIA DE LA ESPECIALIZACION';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."DE_ESPECIALIZACION" IS 'DESCRIPCION DE LA ESPECIALIZACION';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."NO_INSTITUCION" IS 'NOMBRE DE LA INSTITUCION DE LA ESPECIALIZACION';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."CA_HORAS" IS 'CANTIDAD DE HORAS DE DURACION';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."CO_TIPO_ESP" IS 'CODIGO DE TIPO DE ESPECIALIZACION';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."FE_CREACION" IS 'FECHA DE CREACION DEL REGISTRO';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
  
    COMMENT ON COLUMN "RHTD_ESPECIALIZACION"."IN_ER" IS 'INDICADOR DE ENTE RECTOR (1 CON ER  0 SIN ER)';
	
	
	CREATE TABLE "RHTD_PERFIL_ESPECIALIDAD" 
   (  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "CO_ESPECIALIDAD" NUMBER(*,0) NOT NULL ENABLE, 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "SEC_PERFIL_ESPECIALIDAD" NUMBER(*,0), 
   CONSTRAINT "CP_PERFIL_ESPECIALIDAD" PRIMARY KEY ("NU_CONV", "ANO_CONV", "CO_TIPO", "CO_ESPECIALIDAD", "SEC_PERFIL_ESPECIALIDAD")
   )  ;
  
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."CO_ESPECIALIDAD" IS 'CODIGO DE LA ESPECIALIDAD';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_PERFIL_ESPECIALIDAD"."SEC_PERFIL_ESPECIALIDAD" IS 'CODIGO DE PERFIL ESPECIALIDAD';
   
   CREATE TABLE "RHTV_ARCHIVO_CONV" 
   (  "NU_CONV" CHAR(5) NOT NULL ENABLE, 
  "ANO_CONV" CHAR(4) NOT NULL ENABLE, 
  "BL_BRC" BLOB, 
  "BL_LI" BLOB, 
  "BL_REC" BLOB, 
  "BL_RCV" BLOB, 
  "BL_REP" BLOB, 
  "BL_COM1" BLOB, 
  "BL_COM2" BLOB, 
  "BL_COM3" BLOB, 
  "US_CREACION" VARCHAR2(20), 
  "FE_CREACION" DATE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
  "CO_TIPO" CHAR(1) NOT NULL ENABLE, 
  "RUTA_BL_BRC" VARCHAR2(100), 
  "RUTA_BL_LI" VARCHAR2(100), 
  "RUTA_BL_REC" VARCHAR2(100), 
  "RUTA_BL_RCV" VARCHAR2(100), 
  "RUTA_BL_REP" VARCHAR2(100), 
  "RUTA_BL_COM1" VARCHAR2(100), 
  "RUTA_BL_COM2" VARCHAR2(100), 
  "RUTA_BL_COM3" VARCHAR2(100), 
   CONSTRAINT "CP_ARCHIVO_CONV" PRIMARY KEY ("NU_CONV", "ANO_CONV", "CO_TIPO")
   ) ;
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."NU_CONV" IS 'NUMERO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."ANO_CONV" IS 'AÑO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_BRC" IS 'ARCHIVO DE BASES-REQUISITOS-CRONOGRAMA';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_LI" IS 'ARCHIVO DE LISTA DE INSCRITOS';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_REC" IS 'ARCHIVO DE RESULTADOS DE EVAL. DE CONOCIMIENTOS';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_RCV" IS 'ARCHIVO DE RESULTADOS DE CALIFICACION CV';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_REP" IS 'ARCHIVO DE RESULTADOS DE ENTREVISTA PERSONAL';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_COM1" IS 'ARCHIVO DE COMUNICADO 1';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_COM2" IS 'ARCHIVO DE COMUNICADO 2';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."BL_COM3" IS 'ARCHIVO DE COMUNICADO 3';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."US_CREACION" IS 'USUARIO CREADOR DE REGISTRO';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."FE_CREACION" IS 'FECHA CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."US_UPDATE" IS 'USUARIO MODIFICADOR DE REGISTRO';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."FE_UPDATE" IS 'FECHA MODIFICACION DE REGISTRO';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."CO_TIPO" IS 'CODIGO DE TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_BRC" IS 'RUTA DEL ARCHIVO DE BASES-REQUISITOS-CRONOGRAMA';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_LI" IS 'RUTA DEL ARCHIVO DE LISTA DE INSCRITOS';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_REC" IS 'RUTA DEL ARCHIVO DE RESULTADOS DE EVAL. DE CONOCIMIENTOS';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_RCV" IS 'RUTA DEL ARCHIVO DE RESULTADOS DE CALIFICACION CV';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_REP" IS 'RUTA DEL ARCHIVO DE RESULTADOS DE ENTREVISTA PERSONAL';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_COM1" IS 'RUTA DEL ARCHIVO DE COMUNICADO 1';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_COM2" IS 'RUTA DEL ARCHIVO DE COMUNICADO 2';
 
   COMMENT ON COLUMN "RHTV_ARCHIVO_CONV"."RUTA_BL_COM3" IS 'RUTA DEL ARCHIVO DE COMUNICADO 3';
 
 CREATE TABLE "RHTD_ASIGNA_CONVOCATORIA" 
   (  "CO_ASISTENTE" VARCHAR2(5), 
  "NU_CONV" CHAR(5), 
  "ANO_CONV" CHAR(4), 
  "CO_TIPO" CHAR(1), 
  "IN_ESTADO" CHAR(1) NOT NULL ENABLE, 
  "US_CREACION" VARCHAR2(20) NOT NULL ENABLE, 
  "FE_CREACION" DATE NOT NULL ENABLE, 
  "US_UPDATE" VARCHAR2(20), 
  "FE_UPDATE" DATE, 
   CONSTRAINT "CP_ASIGNA_CONVOCATORIA" PRIMARY KEY ("CO_ASISTENTE", "NU_CONV", "ANO_CONV", "CO_TIPO")
  
   ) ;
 
  
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."CO_ASISTENTE" IS 'CODIGO DEL ASISTENTE (CODIGO DE EMPLEADO)';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."NU_CONV" IS 'NUMERO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."ANO_CONV" IS 'AÑO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."CO_TIPO" IS 'CODIGO DEL TIPO DE CONVOCATORIA';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."IN_ESTADO" IS 'INDICADOR DE ESTADO (1 ACTIVO  0 INACTIVO)';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."US_CREACION" IS 'USUARIO CREADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."FE_CREACION" IS 'FECHA CREACION DEL REGISTRO (FECHA ASIGNACION)';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."US_UPDATE" IS 'USUARIO MODIFICADOR DEL REGISTRO';
 
   COMMENT ON COLUMN "RHTD_ASIGNA_CONVOCATORIA"."FE_UPDATE" IS 'FECHA MODIFICACION DEL REGISTRO';
 

  
 