-----------------------
--PAQUETE CATEGORIA
-----------------------
create or replace PACKAGE PACK_CATEGORIA
IS

--PROCEDIMIENTO INSERTAR

PROCEDURE INSERTAR(
PR_id_categoria IN CATEGORIA.id_categoria%TYPE,
PRO_nombre_categoria IN CATEGORIA.nombre_categoria%TYPE,
PR_descripcion IN CATEGORIA.descripcion_cat%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);

--PROCEDIMIENTO ACTUALIZAR

PROCEDURE ACTUALIZAR(
PR_id_categoria IN CATEGORIA.id_categoria%TYPE,
PRO_nombre_categoria IN CATEGORIA.nombre_categoria%TYPE,
PR_descripcion_cat IN CATEGORIA.descripcion_cat%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);

--PROCEDIMIENTO ELIMINAR

PROCEDURE ELIMINAR(
PR_id_categoria  IN  CATEGORIA.id_categoria%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);

--PREOCEDIMIENTO OBTENER

PROCEDURE OBTENER(
PR_id_categoria  IN CATEGORIA.id_categoria%TYPE,
PR_conjunto OUT CATEGORIA%ROWTYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);

END PACK_CATEGORIA;

-----------------------
--CUERPO CATEGORIA
-----------------------
create or replace PACKAGE BODY PACK_CATEGORIA

IS

PROCEDURE INSERTAR(
PR_id_categoria IN CATEGORIA.id_categoria%TYPE,
PRO_nombre_categoria IN CATEGORIA.nombre_categoria%TYPE,
PR_descripcion IN CATEGORIA.descripcion_cat%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)

AS
 
 V_VERIFICADOR  NUMBER := 0;
BEGIN 

-- DUPLICACION DE CATEGORIA 

SELECT COUNT(*) INTO V_VERIFICADOR 
FROM  CATEGORIA
 WHERE id_categoria=PR_id_categoria;

IF(V_VERIFICADOR>0)
THEN
RAISE_APPLICATION_ERROR(-200001,'CODIGO CATEGORIA DUPLICADO');
END IF;

--INSERTANDO 
INSERT INTO CATEGORIA(id_categoria ,nombre_categoria,descripcion_cat)
VALUES(PR_id_categoria,PRO_nombre_categoria,PR_descripcion);
 

EXCEPTION

WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN DEVOLVER');

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PROCEDIMIENTO ACTUALIZAR

PROCEDURE ACTUALIZAR(
PR_id_categoria IN CATEGORIA.id_categoria%TYPE,
PRO_nombre_categoria IN CATEGORIA.nombre_categoria%TYPE,
PR_descripcion_cat IN CATEGORIA.descripcion_cat%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS

V_VERIFICADOR NUMBER :=0;

BEGIN

--VERIFICANDO PARA LA ACTUALIZACION

SELECT COUNT(*) INTO V_VERIFICADOR

FROM CATEGORIA 

WHERE id_categoria=PR_id_categoria;

IF(V_VERIFICADOR = 0)
THEN 
RAISE_APPLICATION_ERROR(-20002,'CATEGORIA INEXISTENTE');
END IF;

--ACTUALIZANDO

UPDATE CATEGORIA SET 

nombre_categoria    =  PRO_nombre_categoria,
 
descripcion_cat         = PR_descripcion_cat

WHERE id_categoria=PR_id_categoria;


EXCEPTION

WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ACTUALIZAR');

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

PROCEDURE ELIMINAR(
PR_id_categoria  IN  CATEGORIA.id_categoria%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)

IS

V_VERIFICADOR NUMBER := 0;

BEGIN

--VALIDANDO CODIGO 

SELECT COUNT(*) INTO V_VERIFICADOR 

FROM CATEGORIA 

WHERE id_categoria=PR_id_categoria;

IF (V_VERIFICADOR=0 )
THEN

RAISE_APPLICATION_ERROR(-20003,'CATEGORIA INEXISTENTE');

END IF;

--ELIMINANDO REGISTRO

DELETE FROM CATEGORIA 
WHERE id_categoria=PR_id_categoria;



EXCEPTION

WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ELIMINAR');

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');

END;

------PROCEDIMIENTO OBTENER
PROCEDURE OBTENER(
PR_id_categoria  IN CATEGORIA.id_categoria%TYPE,
PR_conjunto OUT CATEGORIA%ROWTYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)

IS

V_VERIFICADOR NUMBER :=0;
BEGIN

SELECT COUNT (*) INTO V_VERIFICADOR 
FROM CATEGORIA
WHERE  id_categoria= PR_id_categoria;

IF (V_VERIFICADOR=0 )
THEN
RAISE_APPLICATION_ERROR(-20003,'CATEGORIA INEXISTENTE');
END IF;

--OBTENIEDO RESULTADO 
SELECT * INTO PR_conjunto
FROM CATEGORIA
WHERE id_categoria=PR_id_categoria;
PR_RESPUESTA:= 0;
PR_MENSAJE :='CATEGORIA EXITO ';

EXCEPTION

WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ELIMINAR');

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');

END;


END PACK_CATEGORIA;

-------------
--CLIENTE
-------------

CREATE OR REPLACE PACKAGE PACK_CLIENTE
AS
--PROCEDIMIENTO INSERTAR
PROCEDURE INSERTAR
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_nombre_cliente IN CLIENTE.nombre_cliente%TYPE,
PR_apellido_cliente IN CLIENTE.apellido_cliente%TYPE,
PR_direccion_cliente IN CLIENTE.direccion_cliente%TYPE,
PR_localidad_cliente IN CLIENTE.localidad_cliente%TYPE,
PR_region_cliente IN CLIENTE.region_cliente%TYPE,
PR_cos_postal_cliente IN CLIENTE.cos_postal_cliente%TYPE,
PR_pais_cliente IN CLIENTE.pais_cliente%TYPE,
PR_Telefono_cliente IN CLIENTE.Telefono_cliente%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ACTUALIZAR
PROCEDURE ACTUALIZAR
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_nombre_cliente IN CLIENTE.nombre_cliente%TYPE,
PR_apellido_cliente IN CLIENTE.apellido_cliente%TYPE,
PR_direccion_cliente IN CLIENTE.direccion_cliente%TYPE,
PR_localidad_cliente IN CLIENTE.localidad_cliente%TYPE,
PR_region_cliente IN CLIENTE.region_cliente%TYPE,
PR_cos_postal_cliente IN CLIENTE.cos_postal_cliente%TYPE,
PR_pais_cliente IN CLIENTE.pais_cliente%TYPE,
PR_Telefono_cliente IN CLIENTE.Telefono_cliente%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO OBTENER
PROCEDURE OBTENER
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_conjunto OUT CLIENTE%rowtype,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
END PACK_CLIENTE;
---------------------
--CUERPO CLIENTE
---------------------

CREATE OR REPLACE PACKAGE BODY PACK_CLIENTE
AS
--PROCEDIMIENTO INSERTAR
PROCEDURE INSERTAR
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_nombre_cliente IN CLIENTE.nombre_cliente%TYPE,
PR_apellido_cliente IN CLIENTE.apellido_cliente%TYPE,
PR_direccion_cliente IN CLIENTE.direccion_cliente%TYPE,
PR_localidad_cliente IN CLIENTE.localidad_cliente%TYPE,
PR_region_cliente IN CLIENTE.region_cliente%TYPE,
PR_cos_postal_cliente IN CLIENTE.cos_postal_cliente%TYPE,
PR_pais_cliente IN CLIENTE.pais_cliente%TYPE,
PR_Telefono_cliente IN CLIENTE.Telefono_cliente%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER :=0;
BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR
FROM CLIENTE
WHERE PR_id_cliente=id_cliente;
IF(V_VERIFICADOR>0)
THEN
RAISE_APPLICATION_ERROR(-20001,'DUPLICADO');
END IF;
--INSERTANDO DATOS
INSERT INTO CLIENTE(nombre_cliente,apellido_cliente,direccion_cliente,localidad_cliente
,region_cliente,cos_postal_cliente,pais_cliente,Telefono_cliente)
VALUES(PR_nombre_cliente,PR_apellido_cliente,PR_direccion_cliente,PR_localidad_cliente,PR_region_cliente
,PR_cos_postal_cliente,PR_pais_cliente,PR_Telefono_cliente);
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ENCONTRAR');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PROCEDIMIENTO ACTUALIZAR
PROCEDURE ACTUALIZAR
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_nombre_cliente IN CLIENTE.nombre_cliente%TYPE,
PR_apellido_cliente IN CLIENTE.apellido_cliente%TYPE,
PR_direccion_cliente IN CLIENTE.direccion_cliente%TYPE,
PR_localidad_cliente IN CLIENTE.localidad_cliente%TYPE,
PR_region_cliente IN CLIENTE.region_cliente%TYPE,
PR_cos_postal_cliente IN CLIENTE.cos_postal_cliente%TYPE,
PR_pais_cliente IN CLIENTE.pais_cliente%TYPE,
PR_Telefono_cliente IN CLIENTE.Telefono_cliente%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER := 0;
BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR
FROM CLIENTE
WHERE PR_id_cliente=id_cliente;
IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20002,'NO EXISTE');
END IF;
--ACTUALIZANDO
UPDATE CLIENTE SET
nombre_cliente =PR_nombre_cliente,
apellido_cliente =PR_apellido_cliente,
direccion_cliente =PR_direccion_cliente,
localidad_cliente = PR_localidad_cliente,
region_cliente   = PR_region_cliente,
cos_postal_cliente = PR_cos_postal_cliente,
pais_cliente = PR_pais_cliente,
Telefono_cliente = Telefono_cliente
WHERE PR_id_cliente=id_cliente;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN CODIGO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERRO');
END;
--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER := 0;
BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR 
FROM CLIENTE
WHERE PR_id_cliente=id_cliente;
IF(V_VERIFICADOR=0) THEN
RAISE_APPLICATION_ERROR(-20003,'NO EXISTE');
END IF;


--ELIMINANDO

DELETE FROM CLIENTE
WHERE PR_id_cliente=id_cliente;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO PERTENECE');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
--OBTENIENDO
PROCEDURE OBTENER
(
PR_id_cliente IN CLIENTE.id_cliente%TYPE,
PR_conjunto OUT CLIENTE%Rowtype,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER := 0;
BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR 
FROM CLIENTE
WHERE PR_id_cliente= id_cliente;
IF(V_VERIFICADOR = 0)
THEN
RAISE_APPLICATION_ERROR(-20004,'PROVEEDORES INEXISTENTE');
END IF;
--OBTENIENDO
SELECT*INTO PR_conjunto
FROM CLIENTE
WHERE id_cliente=PR_id_cliente;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

END PACK_CLIENTE;
-----------
--EMPLEADO
-----------
CREATE OR REPLACE PACKAGE PACK_EMPLEADOS
AS
--PROCEDIMIENTO INSERTAR 
PROCEDURE INSERTAR
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_nombre_empleado IN EMPLEADOS.nombre_empleado%TYPE,
PR_apellido_empleado IN EMPLEADOS.apellido_empleado%TYPE,
PR_puesto_empleado IN EMPLEADOS.puesto_empleado%TYPE,
PR_direccion_empleado IN EMPLEADOS.direccion_empleado%TYPE,
PR_localidad IN EMPLEADOS.localidad%TYPE,
PR_estado IN EMPLEADOS.estado%TYPE,
PR_cod_postal IN EMPLEADOS.cod_postal%TYPE,
PR_telefono IN EMPLEADOS.telefono%TYPE,
PR_fecha_nacimiento IN EMPLEADOS.fecha_nacimiendo%TYPE,
PR_fecha_contratacion IN EMPLEADOS.fecha_contratacion%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ACTUALIZAR
PROCEDURE ACTUALIZAR 
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_nombre_empleado IN EMPLEADOS.nombre_empleado%TYPE,
PR_apellido_empleado IN EMPLEADOS.apellido_empleado%TYPE,
PR_puesto_empleado IN EMPLEADOS.puesto_empleado%TYPE,
PR_direccion_empleado IN EMPLEADOS.direccion_empleado%TYPE,
PR_localidad IN EMPLEADOS.localidad%TYPE,
PR_estado IN EMPLEADOS.estado%TYPE,
PR_cod_postal IN EMPLEADOS.cod_postal%TYPE,
PR_telefono IN EMPLEADOS.telefono%TYPE,
PR_fecha_nacimiento IN EMPLEADOS.fecha_nacimiendo%TYPE,
PR_fecha_contratacion IN EMPLEADOS.fecha_contratacion%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO OBTENER
PROCEDURE OBTENER
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_conjunto OUT EMPLEADOS%Rowtype,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
END PACK_EMPLEADOS;

----------------
CUERPO EMPLEADO
----------------
CREATE OR REPLACE PACKAGE BODY PACK_EMPLEADOS
AS

--PROCEDIMIENTO INSERTAR 

PROCEDURE INSERTAR
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_nombre_empleado IN EMPLEADOS.nombre_empleado%TYPE,
PR_apellido_empleado IN EMPLEADOS.apellido_empleado%TYPE,
PR_puesto_empleado IN EMPLEADOS.puesto_empleado%TYPE,
PR_direccion_empleado IN EMPLEADOS.direccion_empleado%TYPE,
PR_localidad IN EMPLEADOS.localidad%TYPE,
PR_estado IN EMPLEADOS.estado%TYPE,
PR_cod_postal IN EMPLEADOS.cod_postal%TYPE,
PR_telefono IN EMPLEADOS.telefono%TYPE,
PR_fecha_nacimiento IN EMPLEADOS.fecha_nacimiendo%TYPE,
PR_fecha_contratacion IN EMPLEADOS.fecha_contratacion%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
IS

V_VERIFICADOR NUMBER := 0;
BEGIN

SELECT COUNT (*)  INTO V_VERIFICADOR
FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
IF(V_VERIFICADOR>0)
THEN
RAISE_APPLICATION_ERROR(-20001,'DUPLICADO');
END IF;
--INSERTANDO DATOS
INSERT INTO EMPLEADOS(id_empleado,nombre_empleado,apellido_empleado,puesto_empleado,direccion_empleado
,localidad,estado,cod_postal,telefono,fecha_nacimiendo,fecha_contratacion)
VALUES(PR_id_empleado,PR_nombre_empleado,PR_apellido_empleado,PR_puesto_empleado,PR_direccion_empleado,PR_localidad
,PR_estado,PR_cod_postal,PR_telefono,PR_fecha_nacimiento,PR_fecha_contratacion);
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
--PROCEDIMIENTO ACTUALIZAR
PROCEDURE ACTUALIZAR 
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_nombre_empleado IN EMPLEADOS.nombre_empleado%TYPE,
PR_apellido_empleado IN EMPLEADOS.apellido_empleado%TYPE,
PR_puesto_empleado IN EMPLEADOS.puesto_empleado%TYPE,
PR_direccion_empleado IN EMPLEADOS.direccion_empleado%TYPE,
PR_localidad IN EMPLEADOS.localidad%TYPE,
PR_estado IN EMPLEADOS.estado%TYPE,
PR_cod_postal IN EMPLEADOS.cod_postal%TYPE,
PR_telefono IN EMPLEADOS.telefono%TYPE,
PR_fecha_nacimiento IN EMPLEADOS.fecha_nacimiendo%TYPE,
PR_fecha_contratacion IN EMPLEADOS.fecha_contratacion%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
AS
V_VERIFICADOR NUMBER :=0;
BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR
FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20002,'NO EXISTE');
END IF;

--ACTUALIZANDO
UPDATE EMPLEADOS
SET

nombre_empleado =PR_nombre_empleado,
apellido_empleado=PR_apellido_empleado,
puesto_empleado=PR_puesto_empleado,
direccion_empleado=PR_direccion_empleado,
localidad=PR_localidad,
cod_postal=PR_cod_postal,
telefono=PR_telefono,
fecha_nacimiendo=PR_fecha_nacimiento,
fecha_contratacion=PR_fecha_contratacion
WHERE PR_id_empleado=id_empleado;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
AS
V_VERIFICADOR NUMBER := 0;
BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR
FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20003,'NO ENCONTRADO');
END IF;
--ELIMINANDO
DELETE FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
PROCEDURE OBTENER
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_conjunto OUT EMPLEADOS%Rowtype,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER :=0;
BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR 
FROM EMPLEADOS
WHERE PR_id_empleado= id_empleado;
IF(V_VERIFICADOR = 0)
THEN
RAISE_APPLICATION_ERROR(-20004,'PROVEEDORES INEXISTENTE');
END IF;
--OBTENIENDO
SELECT*INTO PR_conjunto
FROM EMPLEADOS
WHERE id_empleado=PR_id_empleado;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
END PACK_EMPLEADOS;

----------
PRODUCTO
----------
CREATE OR REPLACE PACKAGE BODY PACK_EMPLEADOS
AS

--PROCEDIMIENTO INSERTAR 

PROCEDURE INSERTAR
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_nombre_empleado IN EMPLEADOS.nombre_empleado%TYPE,
PR_apellido_empleado IN EMPLEADOS.apellido_empleado%TYPE,
PR_puesto_empleado IN EMPLEADOS.puesto_empleado%TYPE,
PR_direccion_empleado IN EMPLEADOS.direccion_empleado%TYPE,
PR_localidad IN EMPLEADOS.localidad%TYPE,
PR_estado IN EMPLEADOS.estado%TYPE,
PR_cod_postal IN EMPLEADOS.cod_postal%TYPE,
PR_telefono IN EMPLEADOS.telefono%TYPE,
PR_fecha_nacimiento IN EMPLEADOS.fecha_nacimiendo%TYPE,
PR_fecha_contratacion IN EMPLEADOS.fecha_contratacion%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
IS

V_VERIFICADOR NUMBER := 0;
BEGIN

SELECT COUNT (*)  INTO V_VERIFICADOR
FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
IF(V_VERIFICADOR>0)
THEN
RAISE_APPLICATION_ERROR(-20001,'DUPLICADO');
END IF;
--INSERTANDO DATOS
INSERT INTO EMPLEADOS(id_empleado,nombre_empleado,apellido_empleado,puesto_empleado,direccion_empleado
,localidad,estado,cod_postal,telefono,fecha_nacimiendo,fecha_contratacion)
VALUES(PR_id_empleado,PR_nombre_empleado,PR_apellido_empleado,PR_puesto_empleado,PR_direccion_empleado,PR_localidad
,PR_estado,PR_cod_postal,PR_telefono,PR_fecha_nacimiento,PR_fecha_contratacion);
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
--PROCEDIMIENTO ACTUALIZAR
PROCEDURE ACTUALIZAR 
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_nombre_empleado IN EMPLEADOS.nombre_empleado%TYPE,
PR_apellido_empleado IN EMPLEADOS.apellido_empleado%TYPE,
PR_puesto_empleado IN EMPLEADOS.puesto_empleado%TYPE,
PR_direccion_empleado IN EMPLEADOS.direccion_empleado%TYPE,
PR_localidad IN EMPLEADOS.localidad%TYPE,
PR_estado IN EMPLEADOS.estado%TYPE,
PR_cod_postal IN EMPLEADOS.cod_postal%TYPE,
PR_telefono IN EMPLEADOS.telefono%TYPE,
PR_fecha_nacimiento IN EMPLEADOS.fecha_nacimiendo%TYPE,
PR_fecha_contratacion IN EMPLEADOS.fecha_contratacion%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
AS
V_VERIFICADOR NUMBER :=0;
BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR
FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20002,'NO EXISTE');
END IF;

--ACTUALIZANDO
UPDATE EMPLEADOS
SET

nombre_empleado =PR_nombre_empleado,
apellido_empleado=PR_apellido_empleado,
puesto_empleado=PR_puesto_empleado,
direccion_empleado=PR_direccion_empleado,
localidad=PR_localidad,
cod_postal=PR_cod_postal,
telefono=PR_telefono,
fecha_nacimiendo=PR_fecha_nacimiento,
fecha_contratacion=PR_fecha_contratacion
WHERE PR_id_empleado=id_empleado;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
AS
V_VERIFICADOR NUMBER := 0;
BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR
FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20003,'NO ENCONTRADO');
END IF;
--ELIMINANDO
DELETE FROM EMPLEADOS
WHERE PR_id_empleado=id_empleado;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
PROCEDURE OBTENER
(
PR_id_empleado IN EMPLEADOS.id_empleado%TYPE,
PR_conjunto OUT EMPLEADOS%Rowtype,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER :=0;
BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR 
FROM EMPLEADOS
WHERE PR_id_empleado= id_empleado;
IF(V_VERIFICADOR = 0)
THEN
RAISE_APPLICATION_ERROR(-20004,'PROVEEDORES INEXISTENTE');
END IF;
--OBTENIENDO
SELECT*INTO PR_conjunto
FROM EMPLEADOS
WHERE id_empleado=PR_id_empleado;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
END PACK_EMPLEADOS;

----------------------
--CUERPO PRODUCTO
--------------------
CREATE OR REPLACE PACKAGE BODY PACK_PRODUCTO
AS

--PROCEDIMIENTO INSERTAR

PROCEDURE INSERTAR(
PR_id_producto IN PRODUCTOS.id_producto%TYPE,
PR_nombre_producto IN PRODUCTOS.nombre_producto%TYPE,
PR_precio_unitario IN PRODUCTOS.precio_unitario%TYPE,
PR_unidades_en_stock IN  PRODUCTOS.unidades_en_stock%TYPE,
PR_unidades_pedida IN PRODUCTOS.unidades_pedida%TYPE,
PR_descatalogado IN PRODUCTOS.descatalogado%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
AS
V_VERIFICADOR NUMBER := 0;

BEGIN
SELECT COUNT(*) INTO  V_VERIFICADOR
FROM PRODUCTOS

WHERE id_producto=PR_id_producto;

IF(V_VERIFICADOR>0)
THEN
RAISE_APPLICATION_ERROR(-20001,'DUPLICADO');
END IF;
--insertando
INSERT INTO PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_UNITARIO,UNIDADES_EN_STOCK,UNIDADES_PEDIDA,DESCATALOGADO)
VALUES(PR_ID_PRODUCTO,PR_NOMBRE_PRODUCTO,PR_PRECIO_UNITARIO,PR_UNIDADES_EN_STOCK,PR_UNIDADES_PEDIDA,PR_DESCATALOGADO);

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ACTUALIZAR');

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
--PROCEDIMIENTO ACTUALIZAR

PROCEDURE ACTUALIZAR
(
PR_id_producto IN PRODUCTOS.id_producto%TYPE,
PR_nombre_producto IN PRODUCTOS.nombre_producto%TYPE,
PR_precio_unitario IN PRODUCTOS.precio_unitario%TYPE,
PR_unidades_en_stock IN  PRODUCTOS.unidades_en_stock%TYPE,
PR_unidades_pedida IN PRODUCTOS.unidades_pedida%TYPE,
PR_descatalogado IN PRODUCTOS.descatalogado%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER:= 0; 
BEGIN

SELECT COUNT (*) PRODUCTOS INTO V_VERIFICADOR
FROM PRODUCTOS 
WHERE PR_id_producto=id_producto;
IF(V_VERIFICADOR=0) THEN
RAISE_APPLICATION_ERROR(-20002,'DUPLICADO');
end if;
--ACTUALIZANDO 
UPDATE PRODUCTOS
SET
nombre_producto  =  PR_nombre_producto,
precio_unitario = PR_precio_unitario,
unidades_en_stock = PR_unidades_en_stock,
unidades_pedida = PR_unidades_pedida,
descatalogado = PR_descatalogado
WHERE PR_id_producto=id_producto;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ELIMINAR');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');

END;

--PROCEDIMIENTO ELIMINAR

PROCEDURE ELIMINAR(
PR_id_producto IN PRODUCTOS.id_producto%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER := 0;
BEGIN 
SELECT COUNT(*) INTO V_VERIFICADOR 
FROM PRODUCTOS
WHERE id_producto=PR_id_producto;
IF (V_VERIFICADOR=0 )
THEN
RAISE_APPLICATION_ERROR(-20003,'SIN DATO');
END IF;
--ELIMINANDO REGISTRO

DELETE FROM PRODUCTOS
WHERE id_producto=PR_id_producto;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ELIMINAR');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PROCEDIMIENTO OBTENER
PROCEDURE OBTENER
(
PR_id_producto IN PRODUCTOS.id_producto%TYPE,
PR_conjunto OUT PRODUCTOS%ROWTYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER:=0;
BEGIN 
SELECT COUNT(*)  INTO V_VERIFICADOR 
FROM PRODUCTOS
WHERE id_producto=PR_id_producto;
IF(V_VERIFICADOR =0)
THEN
RAISE_APPLICATION_ERROR(-20004,'SIN DATO');
END IF;

--OBTENIENDO
SELECT * INTO PR_conjunto 
FROM  PRODUCTOS
WHERE id_producto=PR_id_producto;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN ELIMINAR');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');

END;
END PACK_PRODUCTO;
---------------------
--PRODUCTO CATEGORIA
---------------------

CREATE OR REPLACE PACKAGE PACK_PRODUCTO_CATEGORIA
AS
--PROCEDIMIENTO INSERTAR
PROCEDURE INSERTAR(
PR_id_categoria1 IN PRODUCTO_CATEGORIA.id_categoria1%TYPE,
PR_id_producto1 IN PRODUCTO_CATEGORIA.id_producto1%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE   OUT  VARCHAR
);
END PACK_PRODUCTO_CATEGORIA;

----------------------------
--CUERPO PRODUCTO_CATEGORIA
----------------------------
CREATE OR REPLACE PACKAGE BODY PACK_PRODUCTO_CATEGORIA

AS
--PROCEDIMIENTO INSERTAR
PROCEDURE INSERTAR(
PR_id_categoria1 IN PRODUCTO_CATEGORIA.id_categoria1%TYPE,
PR_id_producto1 IN PRODUCTO_CATEGORIA.id_producto1%TYPE,
PR_RESPUESTA  OUT NUMBER,
PR_MENSAJE   OUT  VARCHAR
)
IS 
V_VERIFICADOR NUMBER :=0;
BEGIN 
--VERIFICANDO ID CATEGORIA1
SELECT COUNT(*)  INTO V_VERIFICADOR
FROM PRODUCTO_CATEGORIA 
WHERE id_categoria1=PR_id_categoria1;
IF(V_VERIFICADOR >0) THEN
RAISE_APPLICATION_ERROR(-20005,'CODIGO CATEGORIA NO EXISTE');
END IF;
--VERIFICANDO ID PRODUCTO1
V_VERIFICADOR :=0;
SELECT COUNT(*)  INTO V_VERIFICADOR
FROM PRODUCTO_CATEGORIA 
WHERE id_producto1=PR_id_producto1;
IF(V_VERIFICADOR > 0) THEN
RAISE_APPLICATION_ERROR(-20006,'CODIGO PRODUCTO NO EXISTE');
END IF;
-- INSERTANDO EL REGISTRO
INSERT INTO PRODUCTO_CATEGORIA(id_categoria1,id_producto1) VALUES
(PR_id_categoria1,PR_id_producto1);
EXCEPTION 
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN INSERTAR');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
END PACK_PRODUCTO_CATEGORIA;
---------------
--PROVEEDORES
---------------
CREATE OR REPLACE PACKAGE PACK_PROVEEDORES
AS
--PROCEDIMIENTO INSERTAR
PROCEDURE INSERTAR
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_nombre_proveedor  IN PROVEEDORES.nombre_proveedor%TYPE,
PR_nombre_contacto IN PROVEEDORES.nombre_contacto%TYPE,
PR_puesto_contacto IN PROVEEDORES.puesto_contacto%TYPE,
PR_direccion IN PROVEEDORES.direccion%TYPE,
PR_localidad IN PROVEEDORES.localidad%TYPE,
PR_estado IN PROVEEDORES.estado%TYPE,
PR_cod_postal IN PROVEEDORES.cod_postal%TYPE,
PR_telefono IN PROVEEDORES.telefono%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ACTUALIZAR
PROCEDURE ACTUALIZAR
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_nombre_proveedor  IN PROVEEDORES.nombre_proveedor%TYPE,
PR_nombre_contacto IN PROVEEDORES.nombre_contacto%TYPE,
PR_puesto_contacto IN PROVEEDORES.puesto_contacto%TYPE,
PR_direccion IN PROVEEDORES.direccion%TYPE,
PR_localidad IN PROVEEDORES.localidad%TYPE,
PR_estado IN PROVEEDORES.estado%TYPE,
PR_cod_postal IN PROVEEDORES.cod_postal%TYPE,
PR_telefono IN PROVEEDORES.telefono%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO OBTENER
PROCEDURE OBTENER
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_conjunto OUT PROVEEDORES%ROWTYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
END PACK_PROVEEDORES;
	
--------------------
--CUERPO PROVEEDORES
--------------------
CREATE OR REPLACE PACKAGE BODY PACK_PROVEEDORES

AS

--PROCEDIMIENTO INSERTAR
PROCEDURE INSERTAR
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_nombre_proveedor  IN PROVEEDORES.nombre_proveedor%TYPE,
PR_nombre_contacto IN PROVEEDORES.nombre_contacto%TYPE,
PR_puesto_contacto IN PROVEEDORES.puesto_contacto%TYPE,
PR_direccion IN PROVEEDORES.direccion%TYPE,
PR_localidad IN PROVEEDORES.localidad%TYPE,
PR_estado IN PROVEEDORES.estado%TYPE,
PR_cod_postal IN PROVEEDORES.cod_postal%TYPE,
PR_telefono IN PROVEEDORES.telefono%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS

V_VERIFICADOR NUMBER :=0;
BEGIN 
SELECT COUNT(*) INTO V_VERIFICADOR
FROM PROVEEDORES
WHERE PR_id_proveedores=id_proveedores;
IF(V_VERIFICADOR>0)
THEN
RAISE_APPLICATION_ERROR(-20005,'CODIGO CATEGORIA NO EXISTE');
END IF;
--INSERTANDO DATOS
INSERT INTO PROVEEDORES(id_proveedores,nombre_proveedor,nombre_contacto,puesto_contacto
,direccion,localidad,estado,cod_postal,telefono) 
VALUES(PR_id_proveedores,PR_nombre_proveedor,PR_nombre_contacto,PR_puesto_contacto,PR_direccion
,PR_localidad,PR_estado,PR_cod_postal,PR_telefono);
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('SIN INSERTAR');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
--PROCEDIMIENTO ACTUALIAR
PROCEDURE ACTUALIZAR
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_nombre_proveedor  IN PROVEEDORES.nombre_proveedor%TYPE,
PR_nombre_contacto IN PROVEEDORES.nombre_contacto%TYPE,
PR_puesto_contacto IN PROVEEDORES.puesto_contacto%TYPE,
PR_direccion IN PROVEEDORES.direccion%TYPE,
PR_localidad IN PROVEEDORES.localidad%TYPE,
PR_estado IN PROVEEDORES.estado%TYPE,
PR_cod_postal IN PROVEEDORES.cod_postal%TYPE,
PR_telefono IN PROVEEDORES.telefono%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER :=0;

BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR
FROM PROVEEDORES
WHERE PR_id_proveedores=id_proveedores;
IF(V_VERIFICADOR=0) THEN
RAISE_APPLICATION_ERROR(-20002,'NO SE PUEDE ACTUALIZAR');
END IF;
--ACTUALIZANDO
UPDATE PROVEEDORES
SET
nombre_proveedor = PR_nombre_proveedor,
nombre_contacto =  PR_nombre_contacto,
puesto_contacto = PR_puesto_contacto,
direccion = PR_direccion,
localidad =PR_localidad,
estado =PR_estado,
cod_postal = PR_cod_postal,
telefono = PR_telefono
WHERE PR_id_proveedores=id_proveedores;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ACTUALIZADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PROCEDIMIENTO ELIMINAR

PROCEDURE ELIMINAR
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER := 0;
BEGIN
SELECT  COUNT(*) INTO V_VERIFICADOR
FROM PROVEEDORES
WHERE PR_id_proveedores=id_proveedores;
IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20003,'NO EXISTE');
END IF;

--ELIMINANDO
DELETE  FROM PROVEEDORES
WHERE PR_id_proveedores=id_proveedores;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PROCEDIMIENTO OBTENER
PROCEDURE OBTENER
(
PR_id_proveedores IN PROVEEDORES.id_proveedores%TYPE,
PR_conjunto OUT PROVEEDORES%ROWTYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER :=0 ;
BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR 
FROM PROVEEDORES
WHERE PR_id_proveedores= id_proveedores;
IF(V_VERIFICADOR = 0)
THEN
RAISE_APPLICATION_ERROR(-20004,'PROVEEDORES INEXISTENTE');
END IF;
--OBTENIENDO
SELECT*INTO PR_conjunto
FROM PROVEEDORES
WHERE id_proveedores=PR_id_proveedores;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
END PACK_PROVEEDORES;

-----------------------
--PRODUCTO PROVEEDORES
-----------------------
CREATE OR REPLACE PACKAGE PACK_PRODUCTO_PROVEEDORES
AS

--PROCEDIMIENTO INSERTAR

PROCEDURE INSERTAR(
PR_id_producto2   IN PRODUCTOS_PROVEEDORES.id_producto2%TYPE,
PR_id_proveedores1 IN PRODUCTOS_PROVEEDORES.id_proveedores1%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
);
END PACK_PRODUCTO_PROVEEDORES;

------------------------------
--CUERPO PRODUCTO PROVEEDORES
------------------------------
CREATE OR REPLACE PACKAGE BODY PACK_PRODUCTO_PROVEEDORES
AS

--PROCEDIMIENTO INSERTAR

PROCEDURE INSERTAR(
PR_id_producto2   IN PRODUCTOS_PROVEEDORES.id_producto2%TYPE,
PR_id_proveedores1 IN PRODUCTOS_PROVEEDORES.id_proveedores1%TYPE,
PR_RESPUESTA OUT NUMBER,
PR_MENSAJE OUT VARCHAR2
)
AS
V_VERIFICADOR NUMBER := 0; 
BEGIN 
--VERIFICANDO ID PRODUCTO2
SELECT COUNT(*)  INTO V_VERIFICADOR
FROM PRODUCTOS_PROVEEDORES 
WHERE id_producto2=PR_id_producto2;
IF(V_VERIFICADOR > 0) THEN
RAISE_APPLICATION_ERROR(-20005,'CODIGO NO EXISTE');
END IF;
 --VERIFICANDO ID PROVEEDORES1
V_VERIFICADOR := 0;
SELECT COUNT(*)  INTO V_VERIFICADOR
FROM PRODUCTOS_PROVEEDORES 
WHERE id_proveedores1=PR_id_proveedores1;
IF(V_VERIFICADOR = 0) THEN
RAISE_APPLICATION_ERROR(-20006,'CODIGO PROVEEDORES NO EXISTE');
END IF;
-- INSERTANDO EL REGISTRO
INSERT INTO PRODUCTOS_PROVEEDORES(id_producto2,id_proveedores1) VALUES
(PR_id_producto2,PR_id_proveedores1);

EXCEPTION 
   WHEN NO_DATA_FOUND THEN
   DBMS_OUTPUT.PUT_LINE('SIN INSERTAR');

   WHEN OTHERS THEN
   DBMS_OUTPUT.PUT_LINE('ERROR');
END;
END PACK_PRODUCTO_PROVEEDORES;
---------------------
--TRANSPORTISTA
--------------------
CREATE OR REPLACE PACKAGE PACK_TRANSPORTISTAS
AS
--PROCEDIMIENTO INSERTAR 
PROCEDURE INSERTAR
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_compañia IN TRANSPORTISTAS.commpañia%TYPE,
PR_contacto IN TRANSPORTISTAS.contacto%TYPE,
PR_direccion IN TRANSPORTISTAS.direccion%TYPE,
PR_localidad IN TRANSPORTISTAS.localidad%TYPE,
PR_estado IN TRANSPORTISTAS.estado%TYPE,
PR_cod_postal IN TRANSPORTISTAS.cod_postal%TYPE,
PR_telefono IN TRANSPORTISTAS.telefono%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ACTUALIZAR
PROCEDURE ACTUALIZAR 
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_compañia IN TRANSPORTISTAS.commpañia%TYPE,
PR_contacto IN TRANSPORTISTAS.contacto%TYPE,
PR_direccion IN TRANSPORTISTAS.direccion%TYPE,
PR_localidad IN TRANSPORTISTAS.localidad%TYPE,
PR_estado IN TRANSPORTISTAS.estado%TYPE,
PR_cod_postal IN TRANSPORTISTAS.cod_postal%TYPE,
PR_telefono IN TRANSPORTISTAS.telefono%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
--PROCEDIMIENTO OBTENER
PROCEDURE OBTENER
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_conjunto OUT   TRANSPORTISTAS%ROWTYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
);
END PACK_TRANSPORTISTAS;
----------------------
--CUERPO TRANSPORTISTAS
----------------------
CREATE OR REPLACE PACKAGE BODY PACK_TRANSPORTISTAS
AS

--PROCEDIMIENTO INSERTAR 
PROCEDURE INSERTAR
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_compañia IN TRANSPORTISTAS.commpañia%TYPE,
PR_contacto IN TRANSPORTISTAS.contacto%TYPE,
PR_direccion IN TRANSPORTISTAS.direccion%TYPE,
PR_localidad IN TRANSPORTISTAS.localidad%TYPE,
PR_estado IN TRANSPORTISTAS.estado%TYPE,
PR_cod_postal IN TRANSPORTISTAS.cod_postal%TYPE,
PR_telefono IN TRANSPORTISTAS.telefono%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
AS
V_VERIFICADOR NUMBER :=0;
BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR
FROM TRANSPORTISTAS
WHERE PR_id_transportista=id_transportista;
IF(V_VERIFICADOR>0)
THEN
RAISE_APPLICATION_ERROR(-20001,'DUPLICADO');
END IF;

---INSERTANDO DATOS 
INSERT INTO TRANSPORTISTAS (commpañia,contacto,direccion,localidad,estado,cod_postal
,telefono)

VALUES(PR_compañia,PR_contacto,PR_direccion,PR_localidad,PR_estado,PR_cod_postal
,PR_telefono);
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO PREOCESADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PROCEDIMIENTO ACTUALIZAR

PROCEDURE ACTUALIZAR 
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_compañia IN TRANSPORTISTAS.commpañia%TYPE,
PR_contacto IN TRANSPORTISTAS.contacto%TYPE,
PR_direccion IN TRANSPORTISTAS.direccion%TYPE,
PR_localidad IN TRANSPORTISTAS.localidad%TYPE,
PR_estado IN TRANSPORTISTAS.estado%TYPE,
PR_cod_postal IN TRANSPORTISTAS.cod_postal%TYPE,
PR_telefono IN TRANSPORTISTAS.telefono%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
AS

V_VERIFICADOR  NUMBER:=0;
BEGIN
SELECT COUNT(*) INTO V_VERIFICADOR
FROM TRANSPORTISTAS 
WHERE PR_id_transportista=id_transportista;
IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20002,'NO ENCONTRADO');
END IF;

--ACTUALIZANDO
update  TRANSPORTISTAS SET
commpañia =PR_compañia,
contacto =PR_contacto,
direccion =PR_direccion,
localidad =PR_localidad,
estado =PR_estado,
cod_postal =PR_cod_postal,
telefono =PR_telefono
WHERE PR_id_transportista=id_transportista;
EXCEPTION
WHEN NO_DATA_FOUND
 THEN DBMS_OUTPUT.PUT_LINE('NO PREOCESADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PROCEDIMIENTO ELIMINAR
PROCEDURE ELIMINAR
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
IS
V_VERIFICADOR NUMBER :=0;

BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR
FROM TRANSPORTISTAS
WHERE PR_id_transportista=id_transportista;

IF(V_VERIFICADOR=0)
THEN
RAISE_APPLICATION_ERROR(-20003,'NO ENCONTRADO');
END IF;
--ELIMINANDO
DELETE  FROM TRANSPORTISTAS
WHERE PR_id_transportista=id_transportista;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO PREOCESADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;

--PRODCEIMIENTO OBTENER
PROCEDURE OBTENER
(
PR_id_transportista IN TRANSPORTISTAS.id_transportista%TYPE,
PR_conjunto OUT   TRANSPORTISTAS%ROWTYPE,
PR_RESPUESTA  OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)
IS

V_VERIFICADOR  NUMBER := 0;


BEGIN
SELECT COUNT(*)INTO V_VERIFICADOR 
FROM TRANSPORTISTAS
WHERE PR_id_transportista= id_transportista;
IF(V_VERIFICADOR = 0)
THEN
RAISE_APPLICATION_ERROR(-20004,'PROVEEDORES INEXISTENTE');
END IF;
--OBTENIENDO
SELECT*INTO PR_conjunto
FROM TRANSPORTISTAS
WHERE id_transportista=PR_id_transportista;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END;
END PACK_TRANSPORTISTAS;
