-- CASE

CREATE OR REPLACE FUNCTION SCOTT.FN_NUM_LETRAS
( P_NUM NUMBER )
RETURN VARCHAR2
AS
  V_LETRAS VARCHAR2(200);
BEGIN
  CASE P_NUM
    WHEN 0 THEN V_LETRAS := 'CERO';
    WHEN 1 THEN V_LETRAS := 'UNO';
    WHEN 2 THEN V_LETRAS := 'DOS';
    WHEN 3 THEN V_LETRAS := 'TRES';
    WHEN 4 THEN V_LETRAS := 'CUATRO';
    WHEN 5 THEN V_LETRAS := 'CINCO';
    WHEN 6 THEN V_LETRAS := 'SEIS';
    WHEN 7 THEN V_LETRAS := 'SIETE';
    WHEN 8 THEN V_LETRAS := 'OCHO';
    WHEN 9 THEN V_LETRAS := 'NUEVE';
    ELSE V_LETRAS := 'NO SE';
  END CASE;
  RETURN V_LETRAS;
END;
/

SELECT SCOTT.FN_NUM_LETRAS(15) FROM DUAL;




