-- IF

CREATE OR REPLACE FUNCTION SCOTT.ES_PAR_V1
( P_NUM NUMBER ) 
RETURN VARCHAR2
AS
  V_RPTA VARCHAR2(30);
BEGIN
  V_RPTA := 'SI ES PAR';
  IF MOD( P_NUM, 2 ) = 1 THEN
    V_RPTA := 'NO ES PAR';
  END IF;
  RETURN V_RPTA;
END;
/


SELECT SCOTT.ES_PAR_V1(11) FROM DUAL;


-- IF - ELSE

CREATE OR REPLACE FUNCTION SCOTT.FN_MAYOR
( P_N1 NUMBER, P_N2 NUMBER, P_N3 NUMBER, P_N4 NUMBER )
RETURN NUMBER 
AS
  P_MAYOR NUMBER;
BEGIN
  -- Estableciendo el punto de apoyo
  IF P_N1 > P_N2 THEN
    P_MAYOR := P_N1;
  ELSE
    P_MAYOR := P_N2;
  END IF;
  -- P_N3
  IF P_N3 > P_MAYOR THEN
    P_MAYOR := P_N3;
  END IF;
  -- P_N4
  IF P_N4 > P_MAYOR THEN
    P_MAYOR := P_N4;
  END IF;
  -- RETORNAR RESULTADO
  RETURN P_MAYOR;
END;


SELECT SCOTT.FN_MAYOR(17,67,16,130) FROM DUAL;

