CREATE OR REPLACE FUNCTION SCOTT.FUN_NOTA_CONDICION
(P_NUM NUMBER)
RETURN VARCHAR2
AS

	V_COND VARCHAR2(200);
	
BEGIN

  CASE 
    WHEN P_NUM >= 14.0 AND P_NUM <= 20.0 THEN V_COND :='APROBADO';
    WHEN P_NUM >= 10.0 AND P_NUM <  14.0 THEN V_COND :='ASISTENTE';
    WHEN P_NUM <  10.0 AND P_NUM >= 0.0  THEN V_COND :='DESAPROBADO';
    ELSE V_COND := 'NOTA INVALIDA';
  END CASE;
  
  RETURN V_COND;
  
END;
/




SELECT SCOTT.FUN_NOTA_CONDICION (21) FROM DUAL;