--TAREA 3
CREATE OR REPLACE FUNCTION SCOTT.FN_OBTENER_CONDICION
(P_NOTA NUMBER)
RETURN VARCHAR2
AS
 V_CONDICION VARCHAR2(200);
BEGIN
 CASE 
  WHEN P_NOTA<=20 AND P_NOTA >= 14 THEN V_CONDICION:='APROBADO';
  WHEN P_NOTA < 14 AND P_NOTA>=10  THEN V_CONDICION:='ASISTENTE';
  WHEN P_NOTA < 10 AND P_NOTA >=0 THEN V_CONDICION:='APROBADO';
  ELSE V_CONDICION := 'FUERA DE RANGO';
 END CASE;
 RETURN V_CONDICION;
END;


SELECT SCOTT.FN_OBTENER_CONDICION(21) FROM DUAL;