

CREATE OR REPLACE FUNCTION SCOTT.FN_PROM_MAY
(P_N1 NUMBER, P_N2 NUMBER, P_N3 NUMBER, P_N4 NUMBER)
RETURN NUMBER
AS
	MENOR NUMBER;
	V_PROMEDIO NUMBER;
	
BEGIN

	IF ( P_N1 > P_N2) THEN
		MENOR := P_N2;
	ELSIF (P_N2 > P_N3) THEN
		MENOR := P_N3;
	ELSIF (P_N3> P_N4) THEN
		MENOR := P_N4;
	ELSE
		MENOR := P_N1;
	END IF;
	
	V_PROMEDIO := (P_N1 + P_N2+ P_N3 + P_N4 - MENOR) /3;
	
	RETURN V_PROMEDIO;
END;
/

-- REVISAR LA LOGICA

DECLARE
	v_promedio NUMBER;
BEGIN
	v_promedio := SCOTT.FN_PROM_MAY ( 18,17,10,19);
	dbms_output.PUT_LINE('PROMEDIO: ' || V_PROMEDIO);
END;

