CREATE OR REPLACE PROCEDURE PR_ACTUALIZAR_CEL_CONDUCTOR
(P_DNI     IN  CONDUCTOR.DNI%TYPE,
 P_CELULAR IN  CONDUCTOR.CELULAR%TYPE)
IS
 V_CONTADOR NUMBER:=0;
 V_EXCEP    EXCEPTION;

BEGIN
 SELECT COUNT(CO.IDCONDUCTOR) INTO V_CONTADOR
 FROM TRANSPORTE.CONDUCTOR CO
 WHERE CO.DNI=P_DNI;
 
 IF(V_CONTADOR=0) THEN
   RAISE V_EXCEP;
 END IF;

 UPDATE TRANSPORTE.CONDUCTOR CO
 SET CO.CELULAR=P_CELULAR
 WHERE CO.DNI=P_DNI;

 COMMIT;

 DBMS_OUTPUT.PUT_LINE('PROCESO OK');

EXCEPTION
 WHEN V_EXCEP THEN
 DBMS_OUTPUT.PUT_LINE('DNI NO EXISTE');
END;


--SELECT * FROM TRANSPORTE.CONDUCTOR;
/*
BEGIN
 PR_ACTUALIZAR_CEL_CONDUCTOR('32554432','111111111');
END;
*/