
CREATE OR REPLACE PACKAGE TRANSPORTE.PKG_UTIL AS
	TYPE T_ARRAY_STRING IS TABLE OF VARCHAR2(1000) 
	INDEX BY BINARY_INTEGER;

	FUNCTION SPLIT(P_DATA VARCHAR2, P_DELIMITADOR VARCHAR2 ) 
	RETURN T_ARRAY_STRING;

END PKG_UTIL;

CREATE OR REPLACE PACKAGE BODY TRANSPORTE.PKG_UTIL AS
	FUNCTION SPLIT(P_DATA VARCHAR2, P_DELIMITADOR VARCHAR2 ) 
	RETURN T_ARRAY_STRING
	IS
	    I        NUMBER   := 0;
	    POS      NUMBER   := 0;
	    V_DATA   CLOB     := P_DATA;
	    STRINGS  T_ARRAY_STRING;
	BEGIN
	  V_DATA := TRIM( V_DATA );
	  POS := INSTR( V_DATA, P_DELIMITADOR, 1, 1 );
	  WHILE ( POS != 0) LOOP
	      I := I + 1;
	      STRINGS(I) := SUBSTR( V_DATA, 1, POS - 1 );
	      V_DATA :=  SUBSTR( V_DATA, POS + 1, LENGTH(V_DATA) );
	      pos := INSTR(V_DATA, P_DELIMITADOR, 1, 1);
	      IF POS = 0 THEN
	          STRINGS( I + 1 ) := V_DATA;
	      END IF;    
	  END LOOP;
	  IF I = 0 AND LENGTH( V_DATA ) > 0 THEN
	    STRINGS( I + 1 ) := V_DATA;
	  END IF;
	  RETURN STRINGS;
	END SPLIT;
	
END PKG_UTIL;

CREATE OR REPLACE PROCEDURE PR_INSERTA_PROGRAMACION
( P_DATOS IN VARCHAR2 )
AS
  V_FILAS    PKG_UTIL.T_ARRAY_STRING;
  V_CAMPOS   PKG_UTIL.T_ARRAY_STRING;
  
BEGIN
   
  V_FILAS := PKG_UTIL.SPLIT(P_DATOS,'#');
   
  FOR I IN 1 .. V_FILAS.COUNT LOOP 
    
    V_CAMPOS := PKG_UTIL.SPLIT(V_FILAS(I),'|');
    
    INSERT INTO transporte.programacion p(p.idprogramacion,p.idbus,p.origen,p.destino,p.fechahorasalida,p.tarifa) 
    VALUES(V_CAMPOS(1),V_CAMPOS(2),V_CAMPOS(3),V_CAMPOS(4),TO_DATE(V_CAMPOS(5),'DD-MM-YYYY HH24:MI:SS'),V_CAMPOS(6));
     
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PROCESO OK');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    ROLLBACK;
END;


DECLARE
  V_DATOS VARCHAR2(6000);
BEGIN
  V_DATOS := '36|1|LIMA|PIURA|16-02-2019 21:00|90#37|9|LIMA|TRUJILLO|16-02-2019 21:00|60';
  PR_INSERTA_PROGRAMACION (V_DATOS);
END;
COMMIT;


SELECT * FROM  TRANSPORTE.PROGRAMACION;