
CREATE TABLE PRODUCTO(
	CODIGO_PRODUCTO CHAR(8) NOT NULL,
	NOMBRE_PRODUCTO VARCHAR2(40) NOT NULL,
	DESCRIPCION_PRODUCTO VARCHAR2(40),
	PRECIO_PRODUCTO FLOAT NOT NULL,
	STOCK_PRODUCTO INT NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO)
);

CREATE TABLE CLIENTE(
	DNI_CLIENTE CHAR(8) NOT NULL,
	NOMBRE_CLIENTE VARCHAR(40) NOT NULL,
	APELLIDOS_CLIENTE VARCHAR(40) NOT NULL,
	TELEFONO_CLIENTE CHAR(9),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI_CLIENTE)
);

CREATE TABLE TRABAJADOR(
	CODIGO_TRABAJADOR CHAR(8) NOT NULL,
	NOMBRE_TRABAJADOR VARCHAR(40) NOT NULL,
	APELLIDOS_TRABAJADOR VARCHAR(40) NOT NULL,
	TELEFONO_TRABAJADOR CHAR(9) NOT NULL,
	DIRECCION VARCHAR2(60) NOT NULL,
	USUARIO VARCHAR2(20) NOT NULL,
	CONTRASENA VARCHAR2(8) NOT NULL,
	ROL VARCHAR(20) NOT NULL,
	CONSTRAINT PK_TRABAJADOR PRIMARY KEY (CODIGO_TRABAJADOR)
); 

CREATE TABLE PEDIDO(
	CODIGO_PEDIDO CHAR(8) NOT NULL,
	DNI_CLIENTE CHAR(8) NOT NULL,
	CODIGO_TRABAJADOR CHAR (8) NOT NULL,
	FECHA_PEDIDO DATE NOT NULL,
	FECHA_ENTREGA DATE NOT NULL,
	TOTAL FLOAT NOT NULL,
	CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGO_PEDIDO),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE) ON DELETE CASCADE,	
	CONSTRAINT FK_TRABAJADOR FOREIGN KEY (CODIGO_TRABAJADOR) REFERENCES TRABAJADOR(CODIGO_TRABAJADOR) ON DELETE CASCADE
);

CREATE TABLE PRODUCTO_PEDIDO(
	CODIGO_PEDIDO CHAR(8) NOT NULL,
	CODIGO_PRODUCTO CHAR(8) NOT NULL,
	CANTIDAD INT NOT NULL,
	MONTO FLOAT NOT NULL,
	CONSTRAINT FK_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO) ON DELETE CASCADE,
	CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO) ON DELETE CASCADE,
	CONSTRAINT PK_PRODPED PRIMARY KEY (CODIGO_PEDIDO,CODIGO_PRODUCTO)
);