
		
		/*---------- PAKETE DEL CRUD DEL PRODUCTO----------*/
		
CREATE OR REPLACE PACKAGE Producto_CRUD AS
	
	FUNCTION VERIFICAR_EXISTENCIA_PRODUCTO(
		v_codigoProducto IN PRODUCTO.CODIGO_PRODUCTO%TYPE) RETURN VARCHAR2;
		
	PROCEDURE MOSTRAR_PRODUCTO;
	
	PROCEDURE INSERTAR_PRODUCTO(
		v_codprod IN PRODUCTO.CODIGO_PRODUCTO%TYPE,
		v_nomprod IN PRODUCTO.NOMBRE_PRODUCTO%TYPE,
		v_desprod IN PRODUCTO.DESCRIPCION_PRODUCTO%TYPE,
		v_precioprod IN PRODUCTO.PRECIO_PRODUCTO%TYPE,
		v_stockprod IN PRODUCTO.STOCK_PRODUCTO%TYPE);
	
	PROCEDURE MODIFICAR_PRODUCTO(
		v_codigoProducto IN PRODUCTO.CODIGO_PRODUCTO%TYPE,
		v_nombreProducto IN PRODUCTO.NOMBRE_PRODUCTO%TYPE,
		v_descripcionProducto IN PRODUCTO.DESCRIPCION_PRODUCTO%TYPE,
		v_precioProducto IN PRODUCTO.PRECIO_PRODUCTO%TYPE,
		v_stockProducto IN PRODUCTO.STOCK_PRODUCTO%TYPE);
	
	PROCEDURE ELIMINAR_PRODUCTO(
		v_codigoProducto IN PRODUCTO.CODIGO_PRODUCTO%TYPE);

END Producto_CRUD;
	
		
CREATE OR REPLACE PACKAGE BODY PRODUCTO_CRUD AS
	
	FUNCTION VERIFICAR_EXISTENCIA_PRODUCTO(
		v_codigoProducto IN PRODUCTO.CODIGO_PRODUCTO%TYPE
	) 
		RETURN VARCHAR2
	IS
		v_existeProducto NUMBER:=0;
	BEGIN
		SELECT COUNT(CODIGO_PRODUCTO) INTO v_existeProducto FROM PRODUCTO WHERE CODIGO_PRODUCTO=UPPER(v_codigoProducto);
		IF v_existeProducto>0 THEN	
			RETURN 'True';
		END IF;
		RETURN 'False';
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			DBMS_OUTPUT.PUT_LINE('LA CONSULTA NO DEVUELVE NINGUN VALOR');
		WHEN OTHERS THEN
			DBMS_OUTPUT.PUT_LINE('ERROR DE TIPEO');
	END VERIFICAR_EXISTENCIA_PRODUCTO;
	
	
	
	PROCEDURE MOSTRAR_PRODUCTO
		IS
			v_cantidad NUMBER :=0;
			CURSOR prod_cursor IS SELECT * FROM PRODUCTO;
		BEGIN
			SELECT COUNT(CODIGO_PRODUCTO) INTO v_cantidad FROM PRODUCTO;
			IF v_cantidad>0 THEN
				DBMS_OUTPUT.PUT_LINE('Cantidad de productos: '||v_cantidad);
				DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------------');
				FOR producto_cursor IN prod_cursor LOOP
					
					DBMS_OUTPUT.PUT_LINE('Codigo del producto: '||producto_cursor.CODIGO_PRODUCTO
					||'  -     Nombre Producto: '||producto_cursor.NOMBRE_PRODUCTO
					||'	 -     Descripcion del produucto: '||producto_cursor.DESCRIPCION_PRODUCTO
					||'  -     Precio del producto:'||producto_cursor.PRECIO_PRODUCTO
					||'  -     Stock del producto: '||producto_cursor.STOCK_PRODUCTO);
				END LOOP;
			END IF;
		END MOSTRAR_PRODUCTO;
	
	
	
	PROCEDURE INSERTAR_PRODUCTO
		(v_codprod IN PRODUCTO.CODIGO_PRODUCTO%TYPE,
		v_nomprod IN PRODUCTO.NOMBRE_PRODUCTO%TYPE,
		v_desprod IN PRODUCTO.DESCRIPCION_PRODUCTO%TYPE,
		v_precioprod IN PRODUCTO.PRECIO_PRODUCTO%TYPE,
		v_stockprod IN PRODUCTO.STOCK_PRODUCTO%TYPE)
	IS
		v_verificar VARCHAR2(5);
	BEGIN
		v_verificar:=VERIFICAREXISTENCIAPRODUCTO(v_codprod);
		IF v_verificar<>'True' THEN
			INSERT INTO PRODUCTO VALUES(v_codprod,v_nomprod,v_desprod,v_precioprod,v_stockprod);
			DBMS_OUTPUT.PUT_LINE('SE INGRESO CORRECTAMENTE EL PRODUCTO.');
			RETURN;
		END IF;
		DBMS_OUTPUT.PUT_LINE('EL PRODUCTO NO PUEDE SER INGRESADO.');
	END INSERTAR_PRODUCTO;
	
	
	
	PROCEDURE MODIFICAR_PRODUCTO(
	v_codigoProducto IN PRODUCTO.CODIGO_PRODUCTO%TYPE,
	v_nombreProducto IN PRODUCTO.NOMBRE_PRODUCTO%TYPE,
	v_descripcionProducto IN PRODUCTO.DESCRIPCION_PRODUCTO%TYPE,
	v_precioProducto IN PRODUCTO.PRECIO_PRODUCTO%TYPE,
	v_stockProducto IN PRODUCTO.STOCK_PRODUCTO%TYPE
	)
	IS
		v_verificar VARCHAR2(5);
	
	BEGIN
		v_verificar:=VERIFICAREXISTENCIAPRODUCTO(v_codigoProducto);
		IF v_verificar='True' THEN
			
			UPDATE PRODUCTO SET NOMBRE_PRODUCTO=v_nombreProducto, DESCRIPCION_PRODUCTO=v_descripcionProducto,
			PRECIO_PRODUCTO=v_precioProducto, STOCK_PRODUCTO=v_stockProducto
			WHERE CODIGO_PRODUCTO=v_codigoProducto;
			
			DBMS_OUTPUT.PUT_LINE('SE ACTUALIZO CORRECTAMENTE EL PRODUCTO.');
			RETURN;
		END IF;
		DBMS_OUTPUT.PUT_LINE('EL PRODUCTO NO SE ENCUENTRA REGISTRADO.');
	END MODIFICAR_PRODUCTO;
	
	
	
	PROCEDURE ELIMINAR_PRODUCTO(
		v_codigoProducto IN PRODUCTO.CODIGO_PRODUCTO%TYPE
	)
	IS
		v_verificar VARCHAR2(5);
	BEGIN
		v_verificar:=VERIFICAREXISTENCIAPRODUCTO(v_codigoProducto);
		IF v_verificar='True' THEN
			DELETE FROM PRODUCTO WHERE CODIGO_PRODUCTO=v_codigoProducto;
			DBMS_OUTPUT.PUT_LINE('SE ELIMINO CORRECTAMENTE EL PRODUCTO.');
			RETURN;
		END IF;
		DBMS_OUTPUT.PUT_LINE('EL PRODUCTO NO SE ENCUENTRA REGISTRADO.');
	END ELIMINAR_PRODUCTO;
END PRODUCTO_CRUD;
	
